site_name: Grupo 3 - TPPE
site_url: https://felipegf1.github.io/docs-grupo3-tppe/
site_description: Documentação do projeto da disciplina de Técnicas de Programação para Plataformas Emergentes (TPPE)
site_author: Grupo 3
repo_url: https://github.com/felipegf1/docs-grupo3-tppe
repo_name: felipegf1/docs-grupo3-tppe

theme:
  name: material
  language: pt-BR
  icon:
    logo: material/swap-horizontal-bold
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      tip: octicons/light-bulb-16
  palette:
    # Modo Claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro
    # Modo Escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - toc.follow

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: true

nav:
  - Início: index.md
  - Histórias de Usuário:
      - Visão Geral: historias-de-usuario/index.md
      - Criar anúncio de "procura-se": historias-de-usuario/criar-anuncio-procura-se.md
      - Ofertar produto em anúncio: historias-de-usuario/ofertar-produto-em-anuncio.md
